name: ❓ Question
description: Ask a question about anything related to Froge
labels: [Question]

body:
  - type: textarea
    id: description
    attributes:
      label: Question
      description: How can we help?
    validations:
      required: true
